# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/railfence.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1250)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainRail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainRail.setGeometry(QtCore.QRect(260, 110, 301, 71))
        self.plainRail.setObjectName("plainRail")
        self.keyRail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.keyRail.setGeometry(QtCore.QRect(260, 220, 301, 71))
        self.keyRail.setObjectName("keyRail")
        self.cipherRail = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.cipherRail.setGeometry(QtCore.QRect(260, 330, 301, 71))
        self.cipherRail.setObjectName("cipherRail")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 140, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 250, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 340, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 50, 141, 20))
        self.label.setBaseSize(QtCore.QSize(4, 0))
        self.label.setObjectName("label")
        self.enRail = QtWidgets.QPushButton(self.centralwidget)
        self.enRail.setGeometry(QtCore.QRect(240, 480, 75, 23))
        self.enRail.setObjectName("enRail")
        self.deRail = QtWidgets.QPushButton(self.centralwidget)
        self.deRail.setGeometry(QtCore.QRect(440, 480, 75, 23))
        self.deRail.setObjectName("deRail")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text:"))
        self.label.setText(_translate("MainWindow", "RAIL FENCE CIPHER"))
        self.enRail.setText(_translate("MainWindow", "Encrypt"))
        self.deRail.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
