# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/vingenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1310, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 60, 141, 20))
        self.label.setBaseSize(QtCore.QSize(4, 0))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 120, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 230, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 330, 61, 20))
        self.label_4.setObjectName("label_4")
        self.plainVin = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainVin.setGeometry(QtCore.QRect(260, 90, 251, 71))
        self.plainVin.setObjectName("plainVin")
        self.keyVin = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.keyVin.setGeometry(QtCore.QRect(263, 210, 251, 51))
        self.keyVin.setObjectName("keyVin")
        self.plainDe = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainDe.setGeometry(QtCore.QRect(270, 300, 241, 71))
        self.plainDe.setObjectName("plainDe")
        self.VinEn = QtWidgets.QPushButton(self.centralwidget)
        self.VinEn.setGeometry(QtCore.QRect(220, 430, 75, 23))
        self.VinEn.setObjectName("VinEn")
        self.VinDe = QtWidgets.QPushButton(self.centralwidget)
        self.VinDe.setGeometry(QtCore.QRect(430, 430, 75, 23))
        self.VinDe.setObjectName("VinDe")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1310, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Vingenere CIpher"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Key:"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text:"))
        self.VinEn.setText(_translate("MainWindow", "Encrypt"))
        self.VinDe.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
